version: '3.4'
services:
  polkadot.public.dappnode.eth:
    image: 'polkadot.public.dappnode.eth:1.2.1'
    build: ./build
    volumes:
      - 'polkadot:/polkadot'
    environment:
      - EXTRA_OPTS=--name DAppNodeNodler
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
volumes:
  polkadot: {}
