version: '3.4'

services:
    dappnodepackage-polkadot-alexander.public.dappnode.eth:
        image: 'dappnodepackage-polkadot-alexander.public.dappnode.eth:0.0.3'
        build: ./build
        volumes:
            - polkadot:/root/.local/share/polkadot
        environment:
            - EXTRA_OPTS=
        ports:
            - '30333:30333'
            - '9933:9933'
            - '9944:9944'
volumes:
    polkadot: {}
